version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: master
      MYSQL_USER: master
      MYSQL_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
