version: '3'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT_DB}
      MYSQL_DATABASE: ${DATABASE_DB}
      MYSQL_USER: ${USERNAME_DB}
      MYSQL_PASSWORD: ${PASSWORD_DB}
    ports:
      - ${PORT_DB}:${PORT_DB}
    volumes:
      - ./mysql:/var/lib/mysql
